### ISSUE TITLE
"Unable to open config file elevio.con" feilmelding

### ISSUE THREAD

**Issue by simon-cmyk** [ITK-TTK4235/lab_2#2]
Det gjør egentlig ingenting, siden det som står i filen er standardvalget uansett, men det dukker opp en irriterende feilmelding. Dette kan være til bry for elevene.

| Terminal |
|-------|
|![Screenshot from 2024-02-29 09-00-00](https://github.com/ITK-TTK4235/lab_2/assets/80280543/32303bc4-d5f8-4e20-8026-16a8ce72b060)|
| Standard |
| ![Screenshot from 2024-02-29 09-00-10](https://github.com/ITK-TTK4235/lab_2/assets/80280543/02e9b912-f863-4970-85ed-2aefa3d04c0a) |
| Ved fix |

Feilmeldingen kommer ikke dersom man enten flytter elevio.con ut til der makefilen er eller spesifiserer hele stien i elevio.c. Som sagt er det ikke noe som er galt, men synes like vell man burde endre det.

| Fix1 | Fix2 |
|---------|---------|
|![Screenshot from 2024-02-29 09-00-43](https://github.com/ITK-TTK4235/lab_2/assets/80280543/4bf4c7df-9e6d-43c9-9d7e-a94135d196d1)|![Screenshot from 2024-02-29 09-00-57](https://github.com/ITK-TTK4235/lab_2/assets/80280543/31610559-4bee-4a48-abe5-039147986e5a)|

Synes begge er grei, men kanskje lettest med nr 1. 

@Safthemse

**Comment by terjejacobsson** [comment]
Synes du kommer med gode løsninger på problemet, endte opp med å implementere løsning 1
